name: code test coverage

on: [push, pull_request]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest coveralls
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Create and upload coverage data
      env:
         COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      run: |
         for i in $(ls tests/Test*)
         do 
           LOOPBACK=1 INVENTORY="127.0.0.1:8000" DEBUG=0 USER=FOO PASSWORD=Bar coverage run -a $i
           coveralls
         done
